// Code generated by MockGen. DO NOT EDIT.
// Source: command_internal_test.go
//
// Generated by this command:
//
//	mockgen -destination=logger_mock_test.go -package=workceptor -source=command_internal_test.go TestLogger
//

// Package workceptor is a generated GoMock package.
package workceptor

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTestLogger is a mock of TestLogger interface.
type MockTestLogger struct {
	ctrl     *gomock.Controller
	recorder *MockTestLoggerMockRecorder
	isgomock struct{}
}

// MockTestLoggerMockRecorder is the mock recorder for MockTestLogger.
type MockTestLoggerMockRecorder struct {
	mock *MockTestLogger
}

// NewMockTestLogger creates a new mock instance.
func NewMockTestLogger(ctrl *gomock.Controller) *MockTestLogger {
	mock := &MockTestLogger{ctrl: ctrl}
	mock.recorder = &MockTestLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestLogger) EXPECT() *MockTestLoggerMockRecorder {
	return m.recorder
}

// DebugPayload mocks base method.
func (m *MockTestLogger) DebugPayload(level int, payload, unitID, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DebugPayload", level, payload, unitID, source)
}

// DebugPayload indicates an expected call of DebugPayload.
func (mr *MockTestLoggerMockRecorder) DebugPayload(level, payload, unitID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugPayload", reflect.TypeOf((*MockTestLogger)(nil).DebugPayload), level, payload, unitID, source)
}

// Error mocks base method.
func (m *MockTestLogger) Error(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockTestLoggerMockRecorder) Error(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockTestLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockTestLogger) Info(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockTestLoggerMockRecorder) Info(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockTestLogger)(nil).Info), varargs...)
}

// Warning mocks base method.
func (m *MockTestLogger) Warning(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warning", varargs...)
}

// Warning indicates an expected call of Warning.
func (mr *MockTestLoggerMockRecorder) Warning(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*MockTestLogger)(nil).Warning), varargs...)
}
